import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// Human-written analysis and updates from AVI.
const blog = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/blog' }),
  schema: z.object({
    title: z.string(),
    date: z.date(),
    author: z.string().default('Association of Vapers India'),
    summary: z.string().max(280),
    tags: z.array(z.string()).default([]),
    draft: z.boolean().default(false),
  }),
});

// Auto-pulled news items (from Google Alerts / outlet RSS via GitHub Action,
// scripts/fetch-news.mjs). As of 2026-09, this pipeline is fully automated —
// no human review gate. `reviewed` now means "passed the automated filters"
// (scripts/config/blocklist.json for commercial/vendor domains,
// press-wire-domains.json + launch-language patterns for industry press
// releases, and a feed's own `keywordFilter` for relevance), not "a person
// signed off on it" — an explicit site-owner instruction (2026-09) to stop
// gating this collection on human curation. The News index carries a
// standing disclaimer (see src/pages/news/index.astro) that these are
// auto-generated from a wide pool of Indian and international sources and
// do not reflect AVI's own views. `research` and `testimonials` are NOT
// covered by this change — they keep their human review gate below.
const news = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/news' }),
  schema: z.object({
    title: z.string(),
    date: z.date(),
    sourceName: z.string(),        // e.g. "The Hindu"
    sourceUrl: z.string().url(),
    summary: z.string().max(400),  // 1-2 sentence AI-written brief, paraphrased
    topic: z.enum(['policy', 'litigation', 'science', 'industry', 'other']).default('other'),
    reviewed: z.boolean().default(true), // passed automated filtering — see comment above
  }),
});

// Digest paragraphs for the News index — a short "here's the gist" summary
// shown above a cluster of cards, so reading a busy day (or, once it's
// elapsed, a whole week or month) doesn't mean opening every card. Three
// tiers, disambiguated by `type`, each rolling up into the next:
//   - 'daily' (default): one calendar day, updated as news arrives.
//     `date` is that day; filename is YYYY-MM-DD.md.
//   - 'weekly': one ISO week (Monday-Sunday) that has fully elapsed. `date`
//     is the week's Monday, `weekEnd` its Sunday; filename is
//     YYYY-MM-DD-week.md (the -week suffix keeps it from colliding with a
//     daily file on a week whose only day of news falls on that Monday).
//     Generated by scripts/generate-weekly-digest.mjs, run every Monday by
//     .github/workflows/generate-weekly-digest.yml, committed straight to
//     main (no PR/human gate — see the `news` comment above).
//   - 'monthly': one calendar month that has fully elapsed (all its weeks
//     already have weekly digests). `date` is the 1st of the month,
//     `weekEnd` reused as the month's last day; filename is
//     YYYY-MM-01-month.md. Generated by scripts/generate-monthly-digest.mjs,
//     run on the 3rd of each month by
//     .github/workflows/generate-monthly-digest.yml. The News index
//     collapses a month with a monthly digest down to one card, itself
//     expanding to that month's weekly cards (which still expand to their
//     own daily breakdown and articles).
// A day/week/month with no matching entry here just shows its cards with
// no digest paragraph — this can still happen by hand for a specific day
// (a human, or Claude on explicit instruction, writing one directly), the
// automated tiers just don't require it anymore.
const newsDigests = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/news-digests' }),
  schema: z.object({
    type: z.enum(['daily', 'weekly', 'monthly']).default('daily'),
    date: z.date(),
    weekEnd: z.date().optional(), // end of the period: the Sunday for weekly, the month's last day for monthly
    summary: z.string().max(600),
  }),
});

// Auto-pulled research (PubMed / Europe PMC via GitHub Action) with AI brief.
const research = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/research' }),
  schema: z.object({
    title: z.string(),
    authors: z.string(),
    journal: z.string(),
    year: z.number(),
    doi: z.string().optional(),
    pubmedId: z.string().optional(),
    studyType: z.enum([
      'systematic-review', 'meta-analysis', 'rct', 'cohort',
      'cross-sectional', 'policy-report', 'other',
    ]),
    substance: z.array(z.enum(['e-cigarette', 'nicotine-pouch', 'snus', 'combustible', 'general'])).default(['general']),
    brief: z.string().max(500),   // plain-language AI summary, paraphrased not quoted
    relevanceToIndia: z.string().optional(),
    reviewed: z.boolean().default(false),
  }),
});

// Press coverage OF AVI (distinct from `news`, which is coverage of the topic generally).
const press = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/press' }),
  schema: z.object({
    title: z.string(),
    date: z.date(),
    outlet: z.string(),
    url: z.string().url().optional(),   // optional: some archive items are scans, no live URL
    type: z.enum(['coverage', 'op-ed', 'quote', 'interview', 'press-release']),
    archivePdf: z.string().optional(),  // path under /public/archive if the live link is dead
  }),
});

// Litigation AVI has supported — one entry per case/matter, built from the CASE folder archive.
// Most entries name an individual or allied organisation as the petitioner of record,
// not AVI itself — see each entry's notes for AVI's actual documented role.
const litigation = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/litigation' }),
  schema: z.object({
    title: z.string(),          // e.g. "Karnataka High Court — WP 36696/2017"
    state: z.string(),
    court: z.string(),
    filedDate: z.date().optional(),
    status: z.enum(['pending', 'disposed', 'withdrawn', 'superseded-by-peca']),
    outcome: z.string().optional(),
    summary: z.string(),
    documents: z.array(z.object({
      label: z.string(),
      path: z.string(),
    })).default([]),
  }),
});

// Visitor-submitted testimonials on quitting combustible tobacco via vaping or
// nicotine pouches. Submitted through the form at /testimonials, which posts to
// the Cloudflare Pages Function at functions/api/testimonial.js. That function
// deliberately does NOT commit the submitter's email into this repo — only
// name, location and the testimonial text ever reach a content file — and
// opens a PR with `reviewed: false`; a human must flip that flag before a
// testimonial appears on the site. See functions/api/testimonial.js for the
// full submission pipeline and functions/README.md for required setup.
const testimonials = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/testimonials' }),
  schema: z.object({
    name: z.string(),
    location: z.string(),        // city or state, as submitted
    date: z.date(),
    testimonial: z.string().max(2000),
    reviewed: z.boolean().default(false),
    featured: z.boolean().default(false),
  }),
});

// AVI's own mobilisation efforts — protests, seminars, delegations, digital
// campaigns — as distinct from `press` (coverage/statements about AVI) and
// `litigation` (court matters). Built from the Google Drive "AVI Outreach"
// archive (Campaigns/Projects folder) plus vapeindia.org's old campaign
// microsites. Do not mention CAPHRA anywhere in this collection or imply
// AVI is a current member (AVI left CAPHRA and INNCO, Oct 2023) — INNCO may
// be mentioned only in passing, in a verified, historical/past-role framing
// (e.g. Samrat Chowdhery served as INNCO's governing-board president from
// July 2020) — see CLAUDE.md.
const campaigns = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/campaigns' }),
  schema: z.object({
    title: z.string(),
    dateStart: z.date(),
    dateEnd: z.date().optional(),
    type: z.enum(['protest', 'seminar', 'delegation', 'press-conference', 'digital-mobilisation', 'research-drive']),
    cities: z.array(z.string()).default([]),
    summary: z.string().max(400),
    photos: z.array(z.object({
      src: z.string(),
      alt: z.string(),
      caption: z.string().optional(),
      // CSS object-position for the cropped thumbnail (e.g. "50% 15%") —
      // only needed when the default centered crop cuts off the subject,
      // e.g. a full-body shot where a short thumbnail would otherwise crop
      // to the torso instead of the face.
      focus: z.string().optional(),
    })).default([]),
  }),
});

// Formal submissions AVI has made to policymakers and regulators — letters,
// rebuttals to government advisories, and organised calls-to-action aimed at
// legislators — as distinct from `campaigns` (public mobilisation) and
// `press` (media-facing statements). Built from the vapeindia.org archive;
// same CAPHRA/INNCO handling note as `campaigns` above applies here too.
const submissions = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/submissions' }),
  schema: z.object({
    title: z.string(),
    date: z.date(),
    recipient: z.string(),  // e.g. "Union Minister of Health & Family Welfare"
    type: z.enum(['letter', 'rebuttal', 'call-to-action']),
    summary: z.string().max(400),
    archivePdf: z.string().optional(),
  }),
});

// AVI's YouTube uploads, auto-pulled from the channel's public RSS feed
// (https://www.youtube.com/feeds/videos.xml?channel_id=...) by
// scripts/fetch-youtube.mjs via a scheduled GitHub Action
// (.github/workflows/fetch-youtube.yml). No AI/editorial step and no
// review gate, unlike `research`/`testimonials` — this is just metadata
// about AVI's own already-published videos, nothing to vet. Mirrors the
// `news` pipeline's direct-commit pattern (see CLAUDE.md).
const videos = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/videos' }),
  schema: z.object({
    videoId: z.string(),
    title: z.string(),
    publishedDate: z.date(),
    thumbnailUrl: z.string().url(),
    // One-line, human-written (or lightly-edited-from-description) summary
    // of what the video actually covers — YouTube's own video description
    // is mostly repeated channel boilerplate, not something to surface
    // verbatim. Falls back to a generic line when fetch-youtube.mjs can't
    // extract anything past that boilerplate.
    summary: z.string().max(200).default("Watch on AVI's YouTube channel."),
  }),
});

export const collections = { blog, news, newsDigests, research, press, litigation, testimonials, campaigns, submissions, videos };
